---
# tasks file for roles/remotely-agent
- name: Cria C:\temp
  ansible.windows.win_file:
    path: C:\temp
    state: directory

- name: Copia o executável do agente Remotely para hosts alvos
  win_copy:
    src: Remotely_Install.exe
    dest: C:\temp\remotely.exe

- name: Instala o agente Remotely em modo silencioso
  win_shell: '.\remotely.exe -install -quiet -organizationid {{ ORGANIZATION_ID }} -serverurl https://{{SERVER}} -devicegroup {{DEVICE_GROUP}} -force' 
  args:
    chdir: C:\temp


